# Generated by Django 4.2.5 on 2023-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finecap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="quitado",
            field=models.BooleanField(default=False),
        ),
    ]
